name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: amoha250-ford/trigger-jenkins-job@main
      with:
        jenkins-server: "http://34.234.79.119:8080/"
        jenkins-username: "abdul_mo"
        jenkins-pat: 1185e07f430de783cc8872eb293ba1eecf
        jenkins-job: "test-job"
        poll-time: 10 # how often (seconds) to poll the jenkins server for results
        timeout-value: 600 # How long (seconds) to poll before timing out the action
        verbose: true # true/false - turns on extra logging
